Add theme changer
vipulnaik/donations pull request #140
Opened 2022-04-10 21:35 UTC by riceissa

2022-04-10 23:01 UTC, vipulnaik requested changes
Can we reserve space in the pre-JS code (e.g. a blank line) so that the Change color" just replaces the already reserved space rather than pushing things down?

2022-04-11 00:16 UTC, riceissa commented on access-portal/index.php
> +print '<span id="changeThemeMenu" style="display: none;">Change <a href="#" onclick="change_theme_color()">color</a></span>';
`href="javascript:;"` seems to work https://stackoverflow.com/a/7676563/3422337

2022-04-11 00:18 UTC, riceissa commented
I have made the requested changes

2022-04-11 00:37 UTC, vipulnaik requested changes
I'm still seeing the cumulative layout shift on Chrome at https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy (though the other issue is fixed!). I suspect the blank paragraph ends up being ignored by the browser in terms of reserving space. Can you look more into this? Thank you!

2022-04-11 01:13 UTC, riceissa commented
I've tried a unicode thin space now instead. It seems to work when I test it locally (though the page loads too fast for me to tell if it's really working).

2022-04-11 02:02 UTC, vipulnaik approved these changes
Thnaks @riceissa -- this works!

2022-04-11 02:03 UTC, merged

2023-07-01 21:20 UTC, Rms125 commented
👁️👍